---
server:
  port: 1337
  website:
    path: ./website


MongoDB:
  dbname: socketio-example
  collection:
    rooms: rooms
    user: user
  url: mongodb://localhost:27017


test:
  port: 1338
  host: http://localhost
  hostFull: http://localhost:1338
  linkClient: http://localhost:1338/?usertoken=mocha
  linkPartner: http://localhost:1338/?usertoken=mocha2
  room: mocha
  user:
    - token: mocha
      name: mocha
    - token: mocha2
      name: mocha2
  bot:
    headless: true
    profile: TDD
    windowWidth: 1920
    windowHeight: 1080
    exts: ~
...
